### ISSUE TITLE
Build error under Windows

### ISSUE THREAD

**Issue by graphixillusion** [aspect-build/bsdtar-prebuilt#11]
### What happened?

I'm trying to build the source under Windows but i'm getting this error and i still can't understand why:

```
ERROR: C:/users/user/_bazel_user/upv4752j/external/xz~/BUILD.bazel:71:10: Copying files failed: (Exit 1): cmd.exe failed: error executing CopyFile command (from target @@xz~//:copy_config) cmd.exe /C bazel-out\x64_windows-opt\bin\external\xz~\copy_config-cmd.bat
Cannot find the file path
Target @@libarchive~//tar:bsdtar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.797s, Critical Path: 6.61s
INFO: 53 processes: 24 internal, 29 local.
ERROR: Build did NOT complete successfully
```

of course if i try to manually run this command i don't have any errors as the file is in the right place: 

cmd.exe /C bazel-out\x64_windows-opt\bin\external\xz~\copy_config-cmd.bat

So i'm blocket at this point and i can't go any further: any clue on how to resolve this?

### Version

Development (host) and target OS/architectures:
Windows 11 x64

Output of `bazel --version`:
bazel 7.3.1 (installed with scoop)

The problem seems to be only when building the xz's dep: i've manually build all the other deps and everything is working fine.

**Comment by alexeagle** [comment]
We publish an `.exe` https://github.com/aspect-build/bsdtar-prebuilt/releases/tag/v3.7.5-1
and have CI that builds on Windows which you could study and mimic: https://github.com/aspect-build/bsdtar-prebuilt/blob/main/.github/workflows/build.yaml#L40-L57

This repo doesn't really intend to support you building it yourself on your own windows machine.

**Comment by graphixillusion** [comment]
Actually is what i did but as i said i get this error. Btw, thank you anyway

**Comment by alexeagle** [comment]
okay I hope you get it working, but not a bug in terms of what we promised here
