### ISSUE TITLE
[Bug]: 3.7.4-2 release doesn't support --options=zstd:threads=0

### ISSUE THREAD

**Issue by froody** [aspect-build/bsdtar-prebuilt#4]
### What happened?

There was a recent issue in libarchive to add support for zstd:threads=0, see https://github.com/libarchive/libarchive/pull/2083 . The relevant [commit](https://github.com/libarchive/libarchive/commit/3efcadf8865efa2e0c5d44606efda87bfd4835fe) was included in the [3.7.4 release of libarchive](https://github.com/libarchive/libarchive/tree/v3.7.4). Yet running the linux-x86_64 binary from [this release
](https://github.com/aspect-build/bsdtar-prebuilt/releases/tag/v3.7.4-2) doesn't seem to contain the fix.

Maybe there was an issue with compilation? Is it possible that `#if defined(HAVE_SYSCONF) && defined(_SC_NPROCESSORS_ONLN)` is somehow false?

See the steps to reproduce below, running with zstd:threads=256 is considerably faster than zstd:threads=0, when they should be equivalent.

### Version

Development (host) and target OS/architectures:

https://github.com/aspect-build/bsdtar-prebuilt/releases/tag/v3.7.4-2

Ubuntu-22.04, Kernel 6.5.0-35-generic, x86_64

### How to reproduce

```shell
% time ./tar_linux_amd64 --zstd -cf  embed.tar.zst tree_dock_3/
./tar_linux_amd64 --zstd -cf embed.tar.zst tree_dock_3/  7.79s user 4.04s system 124% cpu 9.543 total
% time ./tar_linux_amd64 --zstd --options=zstd:threads=0 -cf  embed.tar.zst tree_dock_3/
./tar_linux_amd64 --zstd --options=zstd:threads=0 -cf embed.tar.zst   7.99s user 3.11s system 136% cpu 8.166 total
% time ./tar_linux_amd64 --zstd --options=zstd:threads=256 -cf  embed.tar.zst tree_dock_3/
./tar_linux_amd64 --zstd --options=zstd:threads=256 -cf embed.tar.zst   9.88s user 3.28s system 512% cpu 2.570 total
% time ./tar_linux_amd64 --zstd --options=zstd:compression-level=19,zstd:threads=256 -cf  embed.tar.zst tree_dock_3/
./tar_linux_amd64 --zstd --options=zstd:compression-level=19,zstd:threads=256  767.75s user 7.28s system 3113% cpu 24.896 total
% du -hs tree_dock_3
1.5G	tree_dock_3
% md5sum tar_linux_amd64
a55dcc31c8d1787f2d1ff9966fb876f4  tar_linux_amd64
% nproc
256
```

**Comment by alexeagle** [comment]
I suspect that https://github.com/bazelbuild/bazel-central-registry/pull/2457 fixes this. Previously we didn't have zstd static-linked into the binary. Please re-open this if you can reproduce on 3.7.4-3
